[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sta-pipeline"
dynamic = ["version"]
readme = "README.md"
license = ""
requires-python = ">=3.6"
dependencies = [
    "click",
    "mrcfile",
    "pandas",
    "starfile",
]

[project.scripts]
sta_alignframes = "src.preprocessing.sta_alignframes:cli"
sta_alignframes_multiprocessing = "src.preprocessing.sta_alignframes_multiprocessing:cli"
sta_batchruntomo = "src.preprocessing.sta_batchruntomo:cli"
sta_ctfplotter = "src.preprocessing.sta_ctfplotter:cli"
sta_defoci = "src.isonet.sta_defoci:cli"
sta_eman2 = "src.eman2.sta_eman2:cli"
sta_fidder = "src.preprocessing.sta_fidder:cli"
sta_isonet = "src.isonet.sta_isonet:cli"
sta_rescale_tiltstack = "src.preprocessing.sta_rescale_tiltstack:cli"

[tool.hatch.version]
path = "tests/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/tests",
]
